{application,presence_adapter_xmpp,
    [{description,"XMPP adapter for presence system integration"},
     {vsn,"0.1.0"},
     {registered,[]},
     {mod,{presence_adapter_xmpp_app,[]}},
     {applications,[kernel,stdlib,presence_core,escalus]},
     {env,
         [{xmpp_host,"localhost"},
          {xmpp_port,5222},
          {xmpp_domain,"localhost"},
          {mongooseim_api_endpoint,"http://localhost:8088"},
          {mongooseim_api_auth,
              [{username,<<"admin">>},{password,<<"secret">>}]},
          {sync_mode,bidirectional},
          {jid_mapping,[{strip_domain,true},{lowercase,true}]},
          {respect_xmpp_priority,true},
          {default_priority,0}]},
     {modules,[]},
     {licenses,["Apache 2.0"]},
     {links,[]}]}.
