{application,presence_api,
             [{description,"HTTP and WebSocket API for presence system"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{presence_api_app,[]}},
              {applications,[kernel,stdlib,cowboy,presence_core,
                             presence_store,jsx]},
              {env,[{http_port,8080},
                    {http_acceptors,100},
                    {ws_idle_timeout,60000},
                    {ws_max_frame_size,65536},
                    {auth_enabled,true},
                    {jwt_secret,<<"change_me_in_production">>},
                    {jwt_algorithm,hs256},
                    {rate_limit,[{max_connections_per_ip,100},
                                 {max_requests_per_minute,1000},
                                 {ws_messages_per_minute,600}]},
                    {cors_enabled,true},
                    {cors_origins,[<<"*">>]},
                    {api_version,"v1"}]},
              {modules,[presence_api_app,presence_api_auth,
                        presence_api_presence_handler,presence_api_rate_limit,
                        presence_api_sup,presence_api_websocket_handler,
                        presence_api_ws_registry]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
