{application,presence_admin,
             [{description,"Admin interface and metrics for presence system"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{presence_admin_app,[]}},
              {applications,[kernel,stdlib,cowboy,presence_core,
                             presence_store,telemetry,telemetry_metrics,
                             telemetry_poller]},
              {env,[{admin_port,9090},
                    {admin_acceptors,10},
                    {admin_auth,[{username,<<"admin">>},
                                 {password,<<"change_me_in_production">>}]},
                    {metrics_enabled,true},
                    {metrics_interval,5000},
                    {telemetry_events,[[presence,user,online],
                                       [presence,user,offline],
                                       [presence,ws,connect],
                                       [presence,ws,disconnect],
                                       [presence,api,request]]},
                    {prometheus_enabled,true},
                    {prometheus_port,9091},
                    {dashboard_enabled,true},
                    {dashboard_refresh_interval,1000}]},
              {modules,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
