{application,presence_core,
             [{description,"Core presence tracking logic and state management"},
              {vsn,"0.1.0"},
              {registered,[presence_registry,presence_sup]},
              {mod,{presence_core_app,[]}},
              {applications,[kernel,stdlib,sasl]},
              {env,[{heartbeat_interval,30000},
                    {offline_timeout,90000},
                    {max_users_per_node,100000}]},
              {modules,[presence_cleanup,presence_core_app,presence_core_sup,
                        presence_registry,presence_registry_owner,
                        presence_tracker,presence_tracker_sup,presence_user,
                        presence_user_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
