{application,prometheus_httpd,
             [{description,"Prometheus.io inets httpd exporter"},
              {vsn,"2.1.15"},
              {registered,[]},
              {applications,[kernel,stdlib,inets,prometheus,accept]},
              {env,[]},
              {modules,[prometheus_http_config,prometheus_http_impl,
                        prometheus_httpd]},
              {mod,{prometheus_httpd,[]}},
              {description,"Expose Prometheus metrics using inets httpd."},
              {licenses,["MIT"]},
              {links,[{"Github",
                       "https://github.com/prometheus-erl/prometheus-httpd"},
                      {"Hex.pm","https://hex.pm/packages/prometheus_httpd"},
                      {"Beam Dashboards",
                       "https://github.com/prometheus-erl/beam-dashboards"},
                      {"Prometheus","https://hex.pm/packages/prometheus"},
                      {"Prometheus.ex",
                       "https://hex.pm/packages/prometheus_ex"},
                      {"Pushgateway client",
                       "https://hex.pm/packages/prometheus_push"},
                      {"Ecto Instrumenter",
                       "https://hex.pm/packages/prometheus_ecto"},
                      {"Phoenix Instrumenter",
                       "https://hex.pm/packages/prometheus_phoenix"},
                      {"Plugs Instrumenter/Exporter",
                       "https://hex.pm/packages/prometheus_plugs"},
                      {"Process info Collector",
                       "https://hex.pm/packages/prometheus_process_collector"}]}]}.
